[package]
name = "{{PROJECT_NAME}}"
version = "0.0.1"
description = "Myco project"

[registries]
myco = { path = "../lib/registry.toml" }

[run]
default = "src"
check = "vendor/@myco/check"
test = "test"

[deps]
"@myco/core" = "0.0.1-SNAPSHOT"
"@myco/check" = "0.0.1-SNAPSHOT"
"@myco/test" = "0.0.1-SNAPSHOT"
