[package]
name = "myco"
version = "0.1.0"
edition = "2021"
description = "Myco runtime for secure server-side TypeScript projects."

[workspace]
# This is a path relative to the workspace root.
members = ["util"]

[workspace.dependencies]
deno_core = "0.185.0"
zip = "0.6.5"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version = "0.8.4", features = ["std_rng"] }
deno_core = { workspace = true }
reqwest = { version = "0.11.17", features = ["blocking"] }
tokio = { version = "1.25.0", features = ["full"] }
toml_edit = "0.19.8"
clap = { version = "4.2.7", features = ["cargo"] }
serde = { version = "1.0.162", features = ["derive"] }
toml = "0.7.3"
base64 = "0.21.0"
anyhow = { version = "1.0.57", features = ["backtrace"] }
once_cell = "1.17.1"
zip = { workspace = true }
util = { path = "util" }
async-recursion = "1.0.4"

[build-dependencies]
deno_core = { workspace = true }
zip = { workspace = true }
util = { path = "util" }

[[bin]]
name = "myco"
