[package]
name = "myco"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version = "0.8.4", features = ["std_rng"] }
deno_core = "0.185.0"
reqwest = "0.11.14"
tokio = { version = "1.25.0", features = ["full"] }
clap = { version = "4.2.7", features = ["cargo"] }
serde = { version = "1.0.162", features = ["derive"] }
toml = "0.7.3"
anyhow = { version = "1.0.57", features = ["backtrace"] }
swc_common = { version = "0.31.6", features = ["tty-emitter", "sourcemap"] }
swc_ecma_ast = "0.103.7"
swc_ecma_codegen = "0.138.17"
swc_ecma_parser = "0.133.14"
swc_ecma_transforms_base = "0.126.20"
swc_ecma_transforms_typescript = "0.176.30"
swc_ecma_visit = "0.89.7"
base64 = "0.21.0"
once_cell = "1.17.1"

[build-dependencies]
deno_core = "0.185.0"
