[package]
name = "myco"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version = "0.8.4", features = ["std_rng"] }
deno_ast = { version = "0.22.0", features = ["transpiling"] }
deno_core = "0.174.0"
reqwest = "0.11.14"
tokio = { version = "1.25.0", features = ["full"] }
clap = { version = "4.2.7", features = ["cargo"] }
serde = { version = "1.0.162", features = ["derive"] }
toml = "0.7.3"

[build-dependencies]
deno_core = "0.174.0"
