[workspace]
members = ["cli", "util"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
anyhow = { version = "1.0.57", features = ["backtrace"] }
deno_core = "0.185.0"
url = "2.3.1"
util = { path = "util" }
zip = "0.6.5"
